name: Test And Deploy Config

on:
  push:
    paths:
      - 'openshift/*.yml'
      - '.github/**'
    tags:
      - dev-xyz

env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.SA_TOKEN_CONFIG }}
  PROJECT: hcap

jobs:
  test:
    name: Test Config
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dry run - Dev
        env:
          OS_NAMESPACE_SUFFIX: dev
        run: |
          oc login --token="$AUTH_TOKEN" --server="$CLUSTER"
          cd "$GITHUB_WORKSPACE"
          make server-config-test

  configDev:
    name: Dev - Update Deployment Config
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      OS_NAMESPACE_SUFFIX: dev
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Apply changes
        run: |
          oc login --token="$AUTH_TOKEN" --server="$CLUSTER"
          cd "$GITHUB_WORKSPACE"
          make server-config
